# action.yml
name: 'MetadataMapper'
description: 'Start MetadataMapper and make Request'
outputs:
  post-result: # id of output
    description: 'result of the post request'
    value: ${{ steps.result.outputs.post-result }}
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
    - name: Build docker images
      run: docker build -t metadatamapper .
      shell: bash
    - name: Run tests
      run: docker run metadatamapper &
      shell: bash
    - id: result
      run: |
        echo test
      shell: sh