description: codemeta schema
scheme: codemeta
format: application/json

mapping:
   - target_key: codeMetaCodeRepository
     source_key: codeRepository
   - target_key: codeMetaProgrammingLanguage
     source_key: programmingLanguage.name
   - target_key: codeMetaRuntimePlatform
     source_key: runtimePlatform
   #- target_key: codeMetaTargetProduct
   #  source_key: targetProduct
   - target_key: codeMetaApplicationCategory
     source_key: applicationCategory
   #- target_key: codeMetaMemoryRequirements
   #  source_key: memoryRequirements
   - target_key: codeMetaOperatingSystem
     source_key: operatingSystem
   #- target_key: codeMetaPermissions
   #  source_key: permissions
   #- target_key: codeMetaProcessorRequirements
   #  source_key: processorRequirements
   - target_key: codeMetaReleaseNotes
     source_key: releaseNotes
   #- target_key: codeMetaSoftwareHelp
   #  source_key: softwareHelp
   - target_key: codeMetaSoftwareRequirementsTitle
     source_key: softwareRequirements[*].name
   - target_key: codeMetaSoftwareRequirementsUrl
     source_key: softwareRequirements[*].provider.url
   #- target_key: codeMetaStorageRequirements
   #  source_key: storageRequirements
   #- target_key: relatedDatasets
   #  source_key: supportingData
   - target_key: authorName
     source_key: 
     - author[*].givenName
     - author[*].familyName
     type: merge
     priority: 1
     join_symbol: " "
   - target_key: authorName
     source_key: author[*].familyName
   - target_key: contributorName
     source_key: 
     - contributor[*].givenName
     - contributor[*].familyName
     type: merge
     priority: 2
     join_symbol: " "
   - target_key: contributorName
     source_key: contributor[*].familyName  
   - target_key: contributorName
     source_key: 
     - copyrightHolder[*].givenName
     - copyrightHolder[*].familyName
     type: merge
     priority: 2
     join_symbol: " "
   - target_key: contributorName
     source_key: copyrightHolder[*].familyName
   - target_key: authorName
     source_key: creator
   - target_key: productionDate
     source_key: dateCreated
   - target_key: distributionDate
     source_key: datePublished
   #- target_key: contributorName
   #  source_key: editor
   - target_key: contributorName
     source_key: funder[*].name
   - target_key: keywordValue
     source_key: keywords
   #- target_key: producerName
   #  source_key: producer
   - target_key: distributorName
     source_key: provider.name
   #- target_key: distributorName
   #  source_key: publisher
   #- target_key: contributorName
   #  source_key: sponsor
   - target_key: relatedDatasets
     source_key: isPartOf
   #- target_key: relatedDatasets
   #  source_key: hasPart
   - target_key: dsDescriptionValue
     source_key: description
   - target_key: title
     source_key: name
   - target_key: otherIdAgency
     source_key: softwareSuggestions[*].sameAs
   - target_key: relatedMaterial
     source_key: relatedLink   
   - target_key: datasetContactEmail
     source_key: maintainer[*].email
   - target_key: authorAffiliation
     source_key: author[*].affiliation.name
   - target_key: codeMetaSoftwareSuggestionsTitle   
     source_key: softwareSuggestions[*].name
   - target_key: codeMetaSoftwareSuggestionsUrl
     source_key: softwareSuggestions[*].provider.url
   - target_key: datasetContactName
     source_key: 
     - maintainer[*].givenName
     - maintainer[*].familyName
     type: merge
     priority: 2
     join_symbol: " "
   - target_key: datasetContactName
     source_key: maintainer[*].familyName  
   - target_key: codeMetaContIntegration
     source_key: contIntegration
   #- target_key: codeMetaBuildInstructions
   #  source_key: buildInstructions
   - target_key: codeMetaDevelopmentStatus
     source_key: developmentStatus
   - target_key: grantNumberAgency
     source_key: funding
   - target_key: codeMetaIssueTracker
     source_key: issueTracker
   - target_key: publicationCitation
     source_key: referencePublication
   #- class: contributorRole
   #  source_key: sponsor
   #  target_key: contributorType
   #  type: addition
   - class: contributorRole
     source_key: funder
     target_key: contributorType
     type: addition  
   #- class: contributorRole
   #  source_key: editor
   #  target_key: contributorType
   #  type: addition   
   - class: contributorRole
     source_key: copyrightHolder
     target_key: contributorType
     type: addition    
     
   - class: DateAdder
     source_key: name
     target_key: dateOfDeposit
     type: addition
  
  

